import json
from app.opensearch_store import OpenSearchStore
from app.redshift_store import RedshiftStore
# Stores embeddings in Redshift as a JSON VARCHAR representation. This keeps the
# warehouse portable across Redshift configurations while preserving the exact
# vectors generated by Sentence Transformers.
os_store=OpenSearchStore(); rs=RedshiftStore()
os_store.ensure_index()
r=os_store.client.search(index=os_store.client.indices.get_alias(index="*").keys().__iter__().__next__(),
                         body={"size":1000,"query":{"match_all":{}}})
for h in r["hits"]["hits"]:
    x=h["_source"]
    vector=json.dumps(x["embedding"])
    safe_text=x["text"].replace("'","''")
    safe_key=x["source_key"].replace("'","''")
    rs.execute(f"""INSERT INTO document_chunks(source_key,chunk_number,text,token_count,embedding)
VALUES ('{safe_key}',{int(x['chunk_number'])},'{safe_text}',{int(x['token_count'])},'{vector.replace("'","''")}')""")
print("Synced",len(r["hits"]["hits"]),"vectors to Redshift.")
